- id: '1730546572911'
  alias: TempOfficeRoomHigh
  description: ''
  triggers:
  - type: temperature
    device_id: 1f8c6d83a2313b8efbb137401eca0d92
    entity_id: 763063287f57b72015d2e8f86c24a2cb
    domain: sensor
    trigger: device
    below: 21
    for:
      hours: 0
      minutes: 10
      seconds: 0
  conditions: []
  actions:
  - action: notify.mobile_app_pixel_4a
    metadata: {}
    data:
      message: Température bureau supérieure à 21°C durant plus de 10 minutes
      title: TempOfficeRoomHigh
  mode: single
- id: '1731099424715'
  alias: Volets Nuit
  description: ''
  triggers:
  - trigger: time_pattern
    hours: '17'
    minutes: '45'
    seconds: '00'
  conditions: []
  actions:
  - device_id: 019b28ce2c08ce00c9e2adcc756c9012
    domain: cover
    entity_id: 93403091719d4bd06280c68e0de6b45d
    type: close
  - device_id: 3db54f0a592324fccf995c5470183ecd
    domain: cover
    entity_id: 39ea2dc9d17d399e360951a2ca6350c2
    type: close
  - device_id: 3d4c7737fcabac4c4ac6040a26590cd2
    domain: cover
    entity_id: 0699146805b458d4f5c23a87e95545c8
    type: close
  - device_id: 56f83d510988c7683bf2f994a0853e0c
    domain: cover
    entity_id: 7340e28c0e674a38b92d479523b97c5a
    type: close
  - device_id: be38acbbe9c405a052ad33618abd9621
    domain: cover
    entity_id: d84d0448588d56f12177f317540edf1f
    type: close
  - device_id: bdd5ce77ced318d3085916e23b0b05c7
    domain: cover
    entity_id: 2631419f8573ad1f7250e925360ec31f
    type: close
  - device_id: 04083c3fb898f2df232f94e0ab47d2e0
    domain: cover
    entity_id: f4e07e675b7b145da57cf44dd189ddd6
    type: close
  mode: single
- id: '1731653878971'
  alias: Jour Semaine
  description: ''
  triggers:
  - trigger: sun
    event: sunrise
    offset: 0
  conditions:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  actions:
  - device_id: 3db54f0a592324fccf995c5470183ecd
    domain: cover
    entity_id: 39ea2dc9d17d399e360951a2ca6350c2
    type: open
  mode: single
- id: '1731779479899'
  alias: Arrêt prise téléviseur salon
  description: ''
  triggers:
  - trigger: time
    at: '19:50:00'
    enabled: false
  conditions: []
  actions:
  - action: media_player.turn_off
    metadata: {}
    data: {}
    target:
      entity_id:
      - media_player.liveboxmediaplayersalon
      - media_player.kodi_rec
  mode: single
- id: '1731838690783'
  alias: Livebox Player chambre stop
  description: ''
  triggers:
  - trigger: time
    at: '11:20:00'
  conditions: []
  actions:
  - action: media_player.turn_off
    metadata: {}
    data: {}
    target:
      entity_id: media_player.liveboxplayerchambre
  mode: single
- id: '1731838763339'
  alias: Kodi Play stop
  description: ''
  triggers:
  - trigger: time
    at: '11:22:00'
  conditions: []
  actions:
  - action: media_player.turn_off
    metadata: {}
    data: {}
    target:
      entity_id: media_player.kodi_play
  mode: single
