# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

media_player:
  - platform: liveboxtvuhd
    name: LiveboxPlayerSalon
    host: 192.168.7.107
    port: 8080
    scan_interval: 30
    country: france
  - platform: liveboxtvuhd
    name: LiveboxPlayerChambre
    host: 192.168.7.108
    port: 8080
    scan_interval: 30
    country: france

remote:
  - platform: liveboxtvuhd
    name: LiveboxPlayerSalon
    host: 192.168.7.107
    port: 8080
    scan_interval: 30
    country: france
  - platform: liveboxtvuhd
    name: LiveboxPlayerChambre
    host: 192.168.7.108
    port: 8080
    scan_interval: 30
    country: france
